### PR TITLE
fix: unicode surrogate pair parsing

### LINKED ISSUE #183: Broken selector with unicode
Input:
```css
.\1D306 { } /* 𝌆 */
```

parsed as `팆`, it is surrogate pair, we need handle this rare use case

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #183

Patch release

### CODE REVIEW

File: src/util/unesc.js [hunk 1]
```diff
@@ -1,11 +1,19 @@
...
+        // NaN means non-codepoint
+        // Workaround erroneous numeric interpretation of +"0x"
+        // eslint-disable-next-line no-self-compare
+        return high !== high || escapedWhitespace
+            ? escaped
+            : high < 0
+                ? // BMP codepoint
+                String.fromCharCode(high + 0x10000)
+                : // Supplemental Plane codepoint (surrogate pair)
+                String.fromCharCode((high >> 10) | 0xd800, (high & 0x3ff) | 0xdc00);
```
Comment (evilebottnawi) [inline src/util/unesc.js]: Jquery port https://github.com/jquery/sizzle/blob/master/src/sizzle.js#L152 (very stable and testing in many env/browsers)
